/* 会話練習の音声ファイル一覧（キー＝フランス語の文、値＝ファイル名）。
   f/：女声（piper fr_FR-siwis-medium）、m/：男声（piper fr_FR-tom-medium）で生成した録音。
   d000〜：対話練習（dialogue.js）のセリフ。 */
window.TALK_AUDIO={
"Comment vous appelez-vous ?": "p000.mp3",
"D'où venez-vous ?": "p001.mp3",
"D'où viens-tu ?": "d053.mp3",
"Où habitez-vous ?": "p003.mp3",
"Comment allez-vous ?": "p004.mp3",
"Oui. Très bien, merci. Et vous ?": "p005.mp3",
"Bonjour ! Comment allez-vous ?": "p006.mp3",
"Qu'est-ce que c'est ?": "p007.mp3",
"Je trouve ça cool.": "p008.mp3",
"Je trouve ça super.": "p009.mp3",
"Je trouve ça génial.": "p010.mp3",
"Je trouve ça bizarre.": "p011.mp3",
"Je trouve ça intéressant.": "p012.mp3",
"Je trouve ça mignon.": "p013.mp3",
"Je trouve ça pratique.": "p014.mp3",
"Je trouve ça incroyable.": "p015.mp3",
"Je trouve ça magnifique.": "p016.mp3",
"Je trouve ça complexe.": "p017.mp3",
"Je trouve ça impressionnant.": "p018.mp3",
"Où se trouve la gare, s'il vous plaît ?": "p019.mp3",
"Où se trouve la poste, s'il vous plaît ?": "p020.mp3",
"Où se trouve le musée, s'il vous plaît ?": "p021.mp3",
"Où se trouve la boulangerie, s'il vous plaît ?": "p022.mp3",
"Allez tout droit.": "p023.mp3",
"Excusez-moi, où se trouve la gare, s'il vous plaît ?": "p024.mp3",
"Tournez à gauche.": "p025.mp3",
"Tournez à droite.": "p026.mp3",
"Traversez la rue.": "p027.mp3",
"Traversez la place.": "p028.mp3",
"Traversez le pont.": "p029.mp3",
"Continuez jusqu'au bout.": "p030.mp3",
"C'est juste à côté de la boulangerie.": "p031.mp3",
"Désolée, je ne suis pas d'ici.": "p032.mp3",
"Pardon, où est la poste ?": "p033.mp3",
"Une baguette, s'il vous plaît !": "p034.mp3",
"Bonjour ! Qu'est-ce que je vous sers ?": "p035.mp3",
"Sur place ou à emporter ?": "p036.mp3",
"Je vais prendre une formule déjeuner.": "p037.mp3",
"Vous avez choisi ?": "p038.mp3",
"L'addition, s'il vous plaît.": "p039.mp3",
"Vous désirez autre chose ?": "p040.mp3",
"Combien je vous dois ?": "p041.mp3",
"Est-ce que je peux avoir du sucre ?": "p042.mp3",
"Qu'est-ce que vous me conseillez ?": "p043.mp3",
"Permettez-moi de me présenter.": "p044.mp3",
"Je vous permets de regarder la télévision.": "p045.mp3",
"Tu connais Isabelle ?": "p046.mp3",
"Vous connaissez Isabelle ?": "p047.mp3",
"Si tu es libre, on pourrait aller au cinéma ?": "p048.mp3",
"Je vais aller au cinéma. Ça te dit ?": "p049.mp3",
"Je t'invite.": "p050.mp3",
"Oh, c'est cher ici… Je n'ai pas beaucoup d'argent.": "p051.mp3",
"On paie séparément.": "p052.mp3",
"Alors, comment on paie ?": "p053.mp3",
"Je ne comprends pas.": "p054.mp3",
"Pouvez-vous répéter ?": "p055.mp3",
"Vous descendez à la prochaine station ?": "p056.mp3",
"Tu vois ce que je veux dire ?": "p057.mp3",
"Qu'est-ce que ça veut dire ?": "p058.mp3",
"Laisse tomber.": "p059.mp3",
"Pardon, qu'est-ce que tu disais ?": "p060.mp3",
"C'est dommage.": "p061.mp3",
"Je ne peux pas venir à ta fête samedi.": "p062.mp3",
"Prends ton temps.": "p063.mp3",
"Attends, je cherche mes clés…": "p064.mp3",
"C'est pour rire.": "p065.mp3",
"Quoi ?! Tu es sérieux ?": "p066.mp3",
"On s'amuse bien.": "p067.mp3",
"Alors, cette soirée, ça se passe bien ?": "p068.mp3",
"Ce n'est pas vrai !": "p069.mp3",
"J'ai gagné au loto !": "p070.mp3",
"Tu me fais rire.": "p071.mp3",
"Tu me fais peur.": "p072.mp3",
"Tu me fais pleurer.": "p073.mp3",
"Je fais semblant de ne pas savoir.": "p074.mp3",
"Tu as l'air fatigué.": "p075.mp3",
"Tu as l'air inquiet.": "p076.mp3",
"On dirait un rêve.": "p077.mp3",
"On dirait un film.": "p078.mp3",
"Ça dépend.": "p079.mp3",
"Tu vas à la plage demain ?": "p080.mp3",
"Ça suffit.": "p081.mp3",
"Ça me fait plaisir.": "p082.mp3",
"Tiens, je t'ai apporté des fleurs.": "p083.mp3",
"Ça m'étonnerait.": "p084.mp3",
"Ça te dit ?": "p085.mp3",
"Ce n'est pas la peine de courir.": "p086.mp3",
"Ça tombe bien.": "p087.mp3",
"J'ai un parapluie en plus, tu en veux ?": "p088.mp3",
"Si ça ne vous dérange pas ...": "p089.mp3",
"Est-ce que je peux vous demander un service ?": "p090.mp3",
"Volontiers !": "p091.mp3",
"Avec plaisir !": "p092.mp3",
"Tu veux un café ?": "p093.mp3",
"Est-ce qu'il est possible d'ouvrir la fenêtre ?": "p094.mp3",
"Merci pour votre aide.": "p095.mp3",
"C'est gentil à vous.": "p096.mp3",
"Attendez, je vais porter votre valise.": "p097.mp3",
"Je vous en prie.": "p098.mp3",
"Merci beaucoup pour votre aide !": "p099.mp3",
"Comment dit-on « ○○ » en français ?": "p100.mp3",
"Laissez-moi réfléchir.": "p101.mp3",
"Alors, vous acceptez notre proposition ?": "p102.mp3",
"Comment dirais-je.": "p103.mp3",
"Ce n'est pas facile à dire.": "p104.mp3",
"C'est vrai que...": "p105.mp3",
"Il me semble que...": "p106.mp3",
"Si j'ai bien compris...": "p107.mp3",
"Moi aussi.": "p108.mp3",
"J'adore le chocolat !": "p109.mp3",
"Je suis pour.": "p110.mp3",
"Tu es pour ou contre ce projet ?": "p111.mp3",
"Je partage votre opinion.": "p112.mp3",
"Je ne suis pas d'accord.": "p113.mp3",
"Les devoirs, c'est complètement inutile !": "p114.mp3",
"Ça ne me dit rien.": "p115.mp3",
"Tu connais Paul Martin ?": "p116.mp3",
"Je n'en ai aucun souvenir.": "p117.mp3",
"Ça m'est égal.": "p118.mp3",
"Tu préfères du thé ou du café ?": "p119.mp3",
"Qu'est-ce que tu vas faire ce week-end ?": "d081.mp3",
"Quand est-ce que ça t'arrange ?": "p121.mp3",
"Vendredi, ça te va ?": "p122.mp3",
"Je suis prise ce jour-là.": "p123.mp3",
"Je suis pris ce jour-là.": "p124.mp3",
"Je serai un peu en retard.": "p125.mp3",
"Tu arrives bientôt ? On t'attend !": "p126.mp3",
"Je voudrais faire une réservation.": "p127.mp3",
"À quelle heure ouvrez-vous ?": "p128.mp3",
"Est-ce que je peux payer par carte ?": "p129.mp3",
"Je peux l'essayer ?": "p130.mp3",
"Pouvez-vous m'aider ?": "p131.mp3",
"Tu as de la chance !": "p132.mp3",
"J'ai trouvé 50 euros dans la rue !": "p133.mp3",
"J'ai honte.": "p134.mp3",
"Tu es tombé devant tout le monde, non ?": "p135.mp3",
"Je te l'avais dit.": "p136.mp3",
"Tu avais raison, il a plu toute la journée.": "p137.mp3",
"Tu as de la mémoire.": "p138.mp3",
"Ton anniversaire, c'est le 3 mai, non ?": "p139.mp3",
"C'est triste.": "p140.mp3",
"Je t'envie.": "p141.mp3",
"Je l'envie.": "p142.mp3",
"Ça m'agace.": "p143.mp3",
"Ton voisin fait encore du bruit ?": "p144.mp3",
"Tu veux venir avec moi ?": "p145.mp3",
"Excusez-moi de vous déranger.": "p146.mp3",
"T'as deux minutes ?": "p147.mp3",
"On peut parler un peu ?": "p148.mp3",
"On se parle plus tard.": "p149.mp3",
"Au revoir ! Merci d'être venue !": "p151.mp3",
"Je te tiens au courant.": "p152.mp3",
"Tu me dis si tu peux venir ?": "p153.mp3",
"Ne vous inquiétez pas.": "p155.mp3",
"Pas de problème.": "p156.mp3",
"Je peux emprunter votre stylo ?": "p157.mp3",
"Je suis vraiment fière de vous.": "p158.mp3",
"Je suis vraiment fier de vous.": "p159.mp3",
"Prenez soin de vous.": "p160.mp3",
"Je suis un peu malade en ce moment.": "p161.mp3",
"Bon courage !": "p162.mp3",
"Demain, j'ai un examen très difficile.": "p163.mp3",
"Bonjour !": "d000.mp3",
"Je m'appelle Camille. Comment tu t'appelles ?": "d001.mp3",
"Je m'appelle Sakura.": "d002.mp3",
"Enchantée ! Ça va ?": "d003.mp3",
"Enchanté ! Ça va ?": "d004.mp3",
"Oui, ça va bien, merci. Et toi ?": "d005.mp3",
"Moi, ça va, merci ! D'où viens-tu ?": "d006.mp3",
"Je viens de Nara.": "d007.mp3",
"Ah bon ? Moi, je viens de Lyon. C'est quoi, la spécialité là-bas ?": "d008.mp3",
"La spécialité, c'est les kakis.": "d009.mp3",
"C'est génial ! À Lyon, la spécialité, c'est la quenelle. Et là-bas, il y a quelque chose à voir ?": "d010.mp3",
"Oui, il y a des cerfs.": "d011.mp3",
"Super ! C'est quand ton anniversaire ?": "d012.mp3",
"Mon anniversaire, c'est le 5 mars.": "d013.mp3",
"Moi, c'est le 14 juillet ! Tu as quel âge ?": "d014.mp3",
"J'ai 19 ans.": "d015.mp3",
"Moi, j'ai vingt ans. Qu'est-ce que tu aimes ?": "d016.mp3",
"J'aime les chats. Je n'aime pas les insectes.": "d017.mp3",
"Ah bon ? Moi, j'aime la musique. Tu es japonaise ?": "d018.mp3",
"Oui, je suis japonaise.": "d019.mp3",
"Moi, je suis française. Quel est ton caractère ?": "d020.mp3",
"Moi, je suis français. Quel est ton caractère ?": "d021.mp3",
"Je suis curieuse.": "d022.mp3",
"Moi, je suis bavarde ! Et moi, je suis comment ?": "d023.mp3",
"Moi, je suis bavard ! Et moi, je suis comment ?": "d024.mp3",
"Je pense que tu es gentille.": "d025.mp3",
"Je pense que tu es gentil.": "d026.mp3",
"Merci, c'est gentil ! Tu as des frères et sœurs ?": "d027.mp3",
"Oui, j'ai une sœur.": "d028.mp3",
"Quel est son caractère ?": "d029.mp3",
"Elle est tranquille.": "d030.mp3",
"Je vois ! À quoi t'intéresses-tu ?": "d031.mp3",
"Je m'intéresse à la littérature.": "d032.mp3",
"Moi, je m'intéresse au Japon ! Merci, c'était super. À bientôt !": "d033.mp3",
"À bientôt !": "d034.mp3",
"Salut ! Ça va ?": "d035.mp3",
"Moi, ça va ! Quelle heure est-il ?": "d036.mp3",
"Il est neuf heures et demie.": "d037.mp3",
"Merci ! Qu'est-ce que tu vas faire ce week-end ?": "d038.mp3",
"Je vais travailler au café.": "d039.mp3",
"Ah bon ? Moi, je vais aller au cinéma. Où es-tu allée pendant les vacances ?": "d040.mp3",
"Je suis allée à Kyoto.": "d041.mp3",
"C'est génial ! Qu'est-ce que tu as fait ?": "d042.mp3",
"J'ai visité un temple.": "d043.mp3",
"Ah, super ! C'était comment ?": "d044.mp3",
"C'était super !": "d045.mp3",
"Génial ! Moi, je suis allée à Paris. C'était super ! Bon, à bientôt !": "d046.mp3",
"Génial ! Moi, je suis allé à Paris. C'était super ! Bon, à bientôt !": "d047.mp3",
"Bonjour ! Vas-y, pose-moi des questions !": "d048.mp3",
"Comment tu t'appelles ?": "d049.mp3",
"Je m'appelle Camille.": "d050.mp3",
"Ça va ?": "d051.mp3",
"Oui, ça va bien, merci !": "d052.mp3",
"Je viens de Lyon.": "d054.mp3",
"C'est quoi, la spécialité là-bas ?": "d055.mp3",
"La spécialité, c'est la quenelle.": "d056.mp3",
"À Lyon, il y a quelque chose à voir ?": "d057.mp3",
"Oui, il y a la basilique de Fourvière.": "d058.mp3",
"C'est quand ton anniversaire ?": "d059.mp3",
"Mon anniversaire, c'est le 14 juillet.": "d060.mp3",
"Tu as quel âge ?": "d061.mp3",
"J'ai vingt ans.": "d062.mp3",
"Qu'est-ce que tu aimes ?": "d063.mp3",
"J'aime la musique. Je n'aime pas les insectes.": "d064.mp3",
"Tu es française ?": "d065.mp3",
"Tu es français ?": "d066.mp3",
"Oui, je suis française.": "d067.mp3",
"Oui, je suis français.": "d068.mp3",
"Quel est ton caractère ?": "d069.mp3",
"Je suis bavarde.": "d070.mp3",
"Je suis bavard.": "d071.mp3",
"Merci, c'est gentil !": "d072.mp3",
"Tu as des frères et sœurs ?": "d073.mp3",
"Oui, j'ai un frère.": "d074.mp3",
"Il est très sérieux.": "d075.mp3",
"À quoi t'intéresses-tu ?": "d076.mp3",
"Je m'intéresse au Japon.": "d077.mp3",
"Salut ! Pose-moi des questions sur mes vacances !": "d078.mp3",
"Quelle heure est-il ?": "d079.mp3",
"Il est trois heures.": "d080.mp3",
"Je vais aller au cinéma.": "d082.mp3",
"Où es-tu allée pendant les vacances ?": "d083.mp3",
"Où es-tu allé pendant les vacances ?": "d084.mp3",
"Je suis allée à Paris.": "d085.mp3",
"Je suis allé à Paris.": "d086.mp3",
"Qu'est-ce que tu as fait ?": "d087.mp3",
"J'ai visité le musée du Louvre.": "d088.mp3",
"C'était comment ?": "d089.mp3",
"C'était génial !": "d090.mp3",
"Merci de m'avoir invitée.": "e000.mp3",
"Prenez votre temps.": "e001.mp3"
};
